app-id: com.bruno.openapi-editor
runtime: org.gnome.Platform
runtime-version: "47"
sdk: org.gnome.Sdk
command: openapi-editor

finish-args:
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  - --device=dri
  - --share=network
  - --filesystem=home

modules:
  - name: openapi-editor
    buildsystem: simple
    build-commands:
      - install -Dm755 openapi-editor /app/bin/openapi-editor
      - install -Dm644 com.bruno.openapi-editor.desktop /app/share/applications/com.bruno.openapi-editor.desktop
      - install -Dm644 com.bruno.openapi-editor.metainfo.xml /app/share/metainfo/com.bruno.openapi-editor.metainfo.xml
      - install -Dm644 icon-128x128.png /app/share/icons/hicolor/128x128/apps/com.bruno.openapi-editor.png
      - install -Dm644 icon-256x256.png /app/share/icons/hicolor/256x256/apps/com.bruno.openapi-editor.png
    sources:
      - type: file
        path: openapi-editor
      - type: file
        path: com.bruno.openapi-editor.desktop
      - type: file
        path: com.bruno.openapi-editor.metainfo.xml
      - type: file
        path: icon-128x128.png
      - type: file
        path: icon-256x256.png
